name: Build All

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install

    - name: Build client
      run: yarn workspace @reporank/api run build

    - name: Build API
      run: yarn workspace @reporank/api run build