name: Test Client

on:
  push:
    branches: [ main ]
    paths:
     - 'client/**'
  pull_request:
    branches: [ main ]
    paths:
     - 'client/**'

jobs:

  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install

    - name: Test client
        uses: cypress-io/github-action@v4
        with:
          project: ./client
          build: yarn workspace @reporank/client run build
          start: yarn workspace @reporank/client run start